name: Validate hassfest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - name: hassfest validation
        uses: "home-assistant/actions/hassfest@master"